#!/bin/bash

# This software made by Andrian Latif 
# become part of open source code
# You can modify or redistribute this program any time you want and it's free 
# even there are no restrictions at all
# appkill version 1.0 

function Main() {
    #input aplikasi yang di ingin di lihat aktifitasnya
    echo -n "Insert name of app you want to kill : " 

    #mengambil inputan dari echo
    read name_app

    DIR_LOCATION=$(pwd)
    TEXT_READ="readtxt.txt"

    # PERINTAH mengrep aplikasi yang sedang running di backround linux dan di masukan kedalam variabel INPUT_ACCEPT
    INPUT_ACCEPT=$(ps -eo pid,user,stat,comm | grep $name_app)

    # PERINTAH UNTUK MENULIS TEXT KE DALAM FILE
    echo $INPUT_ACCEPT >> $TEXT_READ

    for file in $DIR_LOCATION/$TEXT_READ
    do
        #echo "debug ${file}"
        if [ "${file}" == $DIR_LOCATION/$TEXT_READ ]
        then
            # validasi terleih dahulu jika variabelnya kosong maka tidak ada aktifitas program yang jalan dan program tidak akan di lanjutkan
            if [ -z "$INPUT_ACCEPT" ]
            then
                echo "\ Program is not running"
                echo "exit"
                rm -rf $TEXT_READ
                exit
            else
                #mencari jumlah total aplikasi yang sedang running
                COUNTNAMEAPPTOTAL=$(grep -c $name_app $DIR_LOCATION/$TEXT_READ)
                echo "found ${COUNTNAMEAPPTOTAL} with $name_app name defined in ${file}"
                echo "\*---------------------------------------------------------------*/"
                echo "\*---------------------------------------------------------------*/"
                cat $TEXT_READ
                echo "\*---------------------------------------------------------------*/"
                echo "\*---------------------------------------------------------------*/"
                rm -rf $TEXT_READ
                echo -n "It's running, You want to kill it ? (Y/n) :"
                read validate
                    if [[ $validate == "y" || $validate == "Y" ]]
                    then 
                    # kill aplikasi jika lebih dari 1 atau hanya 1 saja yang running di proses dengan looping
                    for (( c=1; c<=${COUNTNAMEAPPTOTAL}; c++ ))
                        do  
                            #kill aplikasi nya
                            pkill $name_app
                        done
                        break
                    else 
                        echo "You choose " $validate
                        echo "exit"
                        break
                    fi
            fi    
        else 
            echo "wrong file directory I am sory ...."
            break
        fi
    done
}

function Bypassvalid(){
      if grep -qs "14.04" /etc/os-release; then
        echo "Ubuntu 14.04 is too old and but it's ok"
        Main
    fi

    if grep -qs "jessie" /etc/os-release; then
        echo "Debian 8 is too old and but it's ok"
        Main
    fi

    if grep -qs "CentOS release 6" /etc/redhat-release; then
        echo "CentOS 6 is too old and but it's ok"
        Main
    fi

    if grep -qs "Ubuntu 16.04" /etc/os-release; then
        echo "Ubuntu 16.04 is detect but but it's ok"
        Main
    fi

    # Detect Debian users running the script with "sh" instead of bash
    if readlink /proc/$$/exe | grep -q "dash"; then
        echo "This script needs to be run with bash, not sh"
        Main
    fi

    # jalankan sebagai root system jika tidak akan di exit programnya
    if [[ "$EUID" -ne 0 ]]; then
        echo "Sorry, you need to run this as root"
        exit
    fi

    if [[ ! -e /dev/net/tun ]]; then
        echo "The TUN device is not available
    You need to enable TUN before running this script"
        exit
    fi

    if [[ -e /etc/debian_version ]]; then
        os=$(cat /etc/debian_version)
        group_name="nogroup"
        echo "Your OS running on "$os "..."
        Main

    elif [[ -e /etc/centos-release || -e /etc/redhat-release ]]; then
        os=$(cat /etc/centos_release)
        group_name="nobody"
        echo "Your OS running on "$os "..."
        Main

    else
        echo "Looks like you aren't running this installer on Debian, Ubuntu or CentOS"
        exit
    fi
}

function ALLAPP(){
    ps -aux | less
}
#jika parameter kosong
if [[ -z "$@" ]];
then 
    echo "You should to give the parameter on command appkill check with 'appkill --help' "
elif [[ $@ == "--help" ]]; then
    echo "1) appkill start (start program)"
    echo "2) appkill version (see the version app)"
    echo "3) appkill -a (see ALL process running)"
    exit
elif [[ $@ == "start" ]]; then
    Bypassvalid
elif [[ $@ == "version" ]]; then
    echo "appkill 1.0 (copy right by Andrian Latif 2019)"
elif [[ $@ == "-a" ]]; then
    ALLAPP
else 
    echo "Cannot validate the parameter '$@'.... try with this command:  'appkill --help'"
fi